# Generated by Django 4.0.6 on 2022-10-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
